/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class AppAssets {
  AppAssets._();

  static const String beef = 'assets/images/beef.png';
  static const String carrot = 'assets/images/carrot.png';
  static const String food = 'assets/images/food.png';
  static const String iceCream = 'assets/images/icecream.png';
  static const String comment25 = 'assets/images/comment25.png';
  static const String comment50 = 'assets/images/comment50.png';
  static const String foodJapanese1 = 'assets/images/food_japanese_1.png';
  static const String foodJapanese2 = 'assets/images/food_japanese_2.png';
  static const String foodJapanese3 = 'assets/images/food_japanese_3.png';
  static const String foodJapanese4 = 'assets/images/food_japanese_4.png';
  static const String foodJapanese5 = 'assets/images/food_japanese_5.png';
  static const String foodJapanese6 = 'assets/images/food_japanese_7.png';
  static const String foodJapanese7 = 'assets/images/food_japanese_8.png';
  static const List<String> foodItems = [
    foodJapanese1,
    foodJapanese2,
    foodJapanese3,
    foodJapanese4,
    foodJapanese5,
    foodJapanese7,
    foodJapanese6,
  ];
}
